score=list(map(int,input().split()))
if score[0]>100: print('hacker'); exit()
if score[1]>100: print('hacker'); exit()
if score[2]>200: print('hacker'); exit()
if score[3]>200: print('hacker'); exit()
if score[4]>300: print('hacker'); exit()
if score[5]>300: print('hacker'); exit()
if score[6]>400: print('hacker'); exit()
if score[7]>400: print('hacker'); exit()
if score[8]>500: print('hacker'); exit()
if sum(score)>=100:print('draw')
else: print('none')