a,b,c=map(int,input().split())
i,j,k=map(int,input().split())
mymin=  (min(a/i, b/j, c/k))
ans1,ans2,ans3=(a-i*mymin,b-j*mymin,c-k*mymin)
if ans1 == int(ans1) : print("%d"%int(ans1),end=' ')
else: print("%.6f"%ans1,end=' ')
if ans2 == int(ans2) : print("%d"%int(ans2),end=' ')
else: print("%.6f"%ans2,end=' ')
if ans3 == int(ans3) : print("%d"%int(ans3),end='')
else: print("%.6f"%ans3,end='')