a,b,c=map(int, input().split())
setnumber=min(a,b,c)
bugers=sorted(list(map(int,input().split())),reverse=True)
side=sorted(list(map(int,input().split())) ,reverse=True)
beverage=sorted(list(map(int,input().split())),reverse=True)
saleprice = int ((sum(bugers[:setnumber]) +sum(side[:setnumber]) +sum(beverage[:setnumber]))*0.9)+sum(bugers[setnumber:]) +sum(side[setnumber:]) +sum(beverage[setnumber:])
originalprice= sum(bugers)+sum(side)+sum(beverage)
print(originalprice)
print(saleprice)